# Generated by Django 3.1.3 on 2020-11-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.URLField(blank=True, max_length=254),
        ),
    ]
