# Generated by Django 3.1.3 on 2020-11-30 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='author',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('default', 'Choose a category'), ('home', 'Home'), ('electronics', 'Electronics'), ('toys', 'Toys'), ('other', 'Other')], default=('default', 'Choose a category'), max_length=254),
        ),
    ]
